package icu.samnyan.aqua.sega.chusan.model.userdata

//@Entity(name = "ChusanNetBattleLog")
//@Table(name = "chusan_net_battle_log")
class Chu3NetBattleLog(
    val roomId: Long = 0,
    val track: Long = 0,
    val selectUserId: Long = 0,
    val selectUserName: String = "",
    val opponentUserId1: Long = 0,
    val opponentUserId2: Long = 0,
    val opponentUserId3: Long = 0,
    val opponentUserName1: String = "",
    val opponentUserName2: String = "",
    val opponentUserName3: String = "",
    val opponentRegionId1: Long = 0,
    val opponentRegionId2: Long = 0,
    val opponentRegionId3: Long = 0,
    val opponentRating1: Long = 0,
    val opponentRating2: Long = 0,
    val opponentRating3: Long = 0,
    val opponentBattleRankId1: Long = 0,
    val opponentBattleRankId2: Long = 0,
    val opponentBattleRankId3: Long = 0,
    val opponentClassEmblemMedal1: Long = 0,
    val opponentClassEmblemMedal2: Long = 0,
    val opponentClassEmblemMedal3: Long = 0,
    val opponentClassEmblemBase1: Long = 0,
    val opponentClassEmblemBase2: Long = 0,
    val opponentClassEmblemBase3: Long = 0,
    val opponentScore1: Long = 0,
    val opponentScore2: Long = 0,
    val opponentScore3: Long = 0,
    val opponentCharaIllustId1: Long = 0,
    val opponentCharaIllustId2: Long = 0,
    val opponentCharaIllustId3: Long = 0,
    val opponentCharaLv1: Long = 0,
    val opponentCharaLv2: Long = 0,
    val opponentCharaLv3: Long = 0,
    val opponentRatingEffectColorId1: Long = 0,
    val opponentRatingEffectColorId2: Long = 0,
    val opponentRatingEffectColorId3: Long = 0,
    val battleRuleId: Long = 0,
    val monthPoLong: Long = 0,
    val eventPoLong: Long = 0
) : Chu3UserEntity()
